# These are supported funding model platforms

github: Sevichecc
ko_fi: https://ko-fi.com/sevichecc
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: https://liberapay.com/SevicheCC/donate
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
